steps:
  # 1. Сборка образа
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lettura-facile:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/lettura-facile:latest', '.']

  # 2. Публикация образа
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lettura-facile:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lettura-facile:latest']

  # 3. Деплой в Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'lettura-facile'
      - '--image'
      - 'gcr.io/$PROJECT_ID/lettura-facile:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

# Добавляем этот блок для исправления ошибки логирования
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/lettura-facile:$COMMIT_SHA'